name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      run: curl -LsSf https://astral.sh/uv/install.sh | sh
    - name: Set up Python
      run: uv venv
    - name: Install dependencies
      run: uv sync
    - name: Run tests
      run: uv run python -m pytest tests/
